require("lib")
require("prototypes.planets.planet")
require("prototypes.planets.planet_arig_map_gen")
require("prototypes.planets.planet_hyarion_map_gen")
require("prototypes.planets.planet_map_gen")
require("prototypes.planets.surface-conditions")
require("prototypes.entities.entities")
require("prototypes.entities.remnants")
require("prototypes.entities.explosions")
require("prototypes.entities.resources")
require("prototypes.entities.transport-belts")
require("prototypes.entities.hyarion-big-mining-drill")
require("prototypes.entities.polisher")
require("prototypes.circuit-connector-definitions")
require("prototypes.item")
require("prototypes.fluid")
require("prototypes.tile.arig-tile")
require("prototypes.tile.hyarion-tile")
require("prototypes.tile.tile-collision-masks")
require("prototypes.categories.recipe-category")
require("prototypes.categories.resource-category")
require("prototypes.item-groups")
require("prototypes.recipe")
require("prototypes.technology")
require("prototypes.autoplace-controls")
require("prototypes.decoratives.decoratives")
require("prototypes.particles")

--------------------- Compat

require("compat.krastorio2-so")
require("compat.resource-spawner-overhaul")
require("compat.aai-industry")
require("compat.bzlead")
require("compat.bztin")
require("compat.crushing-industry")
require("compat.wood-industry")
require("compat.planet-muluna")

if mods["any-planet-start"] then
    APS.add_planet{name = "arig", filename = "__planetaris-unbounded__/compat/any-planet-start.lua", technology = "planet-discovery-arig"}
end