data:extend(
{
        {
        type = "fluid",
        name = "planetaris-sand",
        subgroup = "fluid",
        icon = "__planetaris-unbounded__/graphics/icons/fluid/sand.png",
        order = "b-b[vulcanus-Arig]-d",
        default_temperature = 50,
        max_temperature = 100,
        heat_capacity = "1kJ",
        base_color = {r = 180 / 255, g = 160 / 255, b = 120 / 255},
        flow_color = {r = 200 / 255, g = 180 / 255, b = 140 / 255},
      },
      {
      type = "fluid",
      name = "planetaris-pure-sand",
      subgroup = "fluid",
      icon = "__planetaris-unbounded__/graphics/icons/fluid/pure-sand.png",
      icon_size = 64,
      order = "b-b[vulcanus-Arig]-e",
      default_temperature = 50,
      max_temperature = 100,
      heat_capacity = "1kJ",
      base_color = {r = 200 / 255, g = 180 / 255, b = 140 / 255},
      flow_color = {r = 200 / 255, g = 180 / 255, b = 140 / 255},
    },
    {
      type = "fluid",
      name = "planetaris-polishing-compound",
      subgroup = "fluid",
      icon = "__planetaris-unbounded-assets__/graphics/icons/fluids/polishing-compound.png",
      icon_size = 64,
      order = "f[hyarion]-a",
      default_temperature = 10,
      max_temperature = 100,
      heat_capacity = "200J",
      base_color = {145, 139, 232},
      flow_color = {145, 139, 232},
    },
})