local item_sounds = require("__base__.prototypes.item_sounds")
local space_age_item_sounds = require("__space-age__.prototypes.item_sounds")
local item_tints = require("__base__.prototypes.item-tints")
local item_effects = require("__space-age__.prototypes.item-effects")
-- local planetaris_item_effects = require("prototypes.item-effects")

data:extend({
{
    ------------------- Arig
    type = "item",
    name = "planetaris-press",
    icon = "__planetaris-arig__/graphics/icons/press.png",
    subgroup = "arig-production",
    order = "a-b",
    inventory_move_sound = item_sounds.fluid_inventory_move,
    pick_sound = item_sounds.fluid_inventory_pickup,
    drop_sound = item_sounds.fluid_inventory_move,
    place_result = "planetaris-press",
    stack_size = 50,
    default_import_location = "arig",
  },
{
    type = "item",
    name = "planetaris-sifter",
    icon = "__planetaris-arig__/graphics/icons/sifter.png",
    subgroup = "arig-production",
    order = "a-a-a",
    inventory_move_sound = item_sounds.fluid_inventory_move,
    pick_sound = item_sounds.fluid_inventory_pickup,
    drop_sound = item_sounds.fluid_inventory_move,
    place_result = "planetaris-sifter",
    stack_size = 10,
    default_import_location = "arig",
  },
    {
    type = "item",
    name = "planetaris-sandstone-brick",
    icon = "__planetaris-arig__/graphics/icons/sandstone-brick.png",
    subgroup = "terrain",
    order = "d[sandstone_brick]",
    icon_size = 64,
    stack_size = 100,
    weight = 10 * kg,
    default_import_location = "arig",
    place_as_tile = {
        result = "planetaris-sandstone-path",
        condition_size = 1,
        condition = {layers={water_tile=true}}
    },
    drop_sound = {
        aggregation = {
            max_count = 1,
            remove = true
        },
        filename = "__base__/sound/item/concrete-inventory-move.ogg",
        volume = 0.6
    },
    pick_sound = {
        aggregation = {
            max_count = 1,
            remove = true
        },
        filename = "__base__/sound/item/concrete-inventory-pickup.ogg",
        volume = 0.8
    },
    inventory_move_sound = {
        filename = "__base__/sound/item/concrete-inventory-move.ogg",
        volume = 0.5
    }},
    {
        type = "item",
        name = "planetaris-sandstone-foundation",
        icon = "__planetaris-arig__/graphics/icons/sandstone-foundation.png",
        subgroup = "terrain",
        order = "d[sandstone_brick]-b",
        stack_size = 100,
        weight = 10 * kg,
        place_as_tile = {
            result = "planetaris-sandstone-foundation",
            condition_size = 1,
            condition = {layers = {ground_tile = true}},
            tile_condition = {"arig-sand"}
        },
        inventory_move_sound = item_sounds.landfill_inventory_move,
        pick_sound = item_sounds.landfill_inventory_pickup,
        drop_sound = item_sounds.landfill_inventory_move,
    },
        {
      type = "item",
      name = "planetaris-cactus-seeds",
      icon = "__planetaris-arig__/graphics/icons/cactus-seeds.png",
      pictures =
      {
        { size = 64, filename = "__planetaris-arig__/graphics/icons/cactus-seeds-1.png", scale = 0.5, mipmap_count = 4 },
        { size = 64, filename = "__planetaris-arig__/graphics/icons/cactus-seeds-2.png", scale = 0.5, mipmap_count = 4 },
        { size = 64, filename = "__planetaris-arig__/graphics/icons/cactus-seeds-3.png", scale = 0.5, mipmap_count = 4 },
        { size = 64, filename = "__planetaris-arig__/graphics/icons/cactus-seeds-4.png", scale = 0.5, mipmap_count = 4 },
      },
      subgroup = "arig-processes",
      order = "a[basic]-a-a",
      plant_result = "planetaris-cactus-plant",
      place_result = "planetaris-cactus-plant",
      inventory_move_sound = space_age_item_sounds.agriculture_inventory_move,
      pick_sound = space_age_item_sounds.agriculture_inventory_pickup,
      drop_sound = space_age_item_sounds.agriculture_inventory_move,
      stack_size = 10,
      default_import_location = "arig",
      weight = 10 * kg,
      fuel_category = "chemical",
      fuel_value = "4MJ"
    },
    {
        type = "capsule",
        name = "planetaris-cactus",
        icon = "__planetaris-arig__/graphics/icons/cactus.png",
        subgroup = "arig-processes",
        order = "a[basic]-a-a-b",
        stack_size = 100,
        weight = 1*kg,
        default_import_location = "arig",
        pictures =
        {
          { size = 64, filename = "__planetaris-arig__/graphics/icons/cactus.png",   scale = 0.5, mipmap_count = 4 },
          { size = 64, filename = "__planetaris-arig__/graphics/icons/cactus-2.png", scale = 0.5, mipmap_count = 4 },
          { size = 64, filename = "__planetaris-arig__/graphics/icons/cactus-3.png", scale = 0.5, mipmap_count = 4 },
          { size = 64, filename = "__planetaris-arig__/graphics/icons/cactus-4.png", scale = 0.5, mipmap_count = 4 },
        },
        fuel_category = "chemical",
        fuel_value = "2MJ",
        capsule_action = item_effects.jellynut_speed,
        spoil_ticks = 60 * minute,
        spoil_result = "spoilage",

        inventory_move_sound = space_age_item_sounds.agriculture_inventory_move,
        pick_sound = space_age_item_sounds.agriculture_inventory_pickup,
        drop_sound = space_age_item_sounds.agriculture_inventory_move,
    },
    {
        type = "item",
        name = "planetaris-glass-panel",
        icon = "__planetaris-arig__/graphics/icons/glass-panel.png",
        subgroup = "arig-processes",
        order = "a[sand-processing]-a[sifting]-d",
        stack_size = 100,
        weight = 5*kg,
        default_import_location = "arig",

        inventory_move_sound = item_sounds.low_density_inventory_move,
        pick_sound = item_sounds.low_density_inventory_pickup,
        drop_sound = item_sounds.low_density_inventory_move,
    },
    {
        type = "item",
        name = "planetaris-heavy-glass",
        icon = "__planetaris-arig__/graphics/icons/heavy-glass.png",
        subgroup = "arig-processes",
        order = "c[advance]-a",
        stack_size = 50,
        weight = 10*kg,
        default_import_location = "arig",

        inventory_move_sound = item_sounds.metal_small_inventory_move,
        pick_sound = item_sounds.metal_small_inventory_pickup,
        drop_sound = item_sounds.metal_small_inventory_move,
        random_tint_color = item_tints.iron_rust,
    },
    {
        type = "item",
        name = "planetaris-raw-quartz",
        icon = "__planetaris-arig__/graphics/icons/quartz.png",
        subgroup = "arig-processes",
        order = "a[basic]-b-b",
        stack_size = 100,
        weight = 5*kg,
        default_import_location = "arig",

        inventory_move_sound = item_sounds.sulfur_inventory_move,
        pick_sound = item_sounds.resource_inventory_pickup,
        drop_sound = item_sounds.sulfur_inventory_move,
    },
    {
        type = "item",
        name = "planetaris-silica",
        icon = "__planetaris-arig__/graphics/icons/silica.png",
        subgroup = "arig-processes",
        order = "c[advance]-b",
        stack_size = 100,
        default_import_location = "arig",

        inventory_move_sound = item_sounds.sulfur_inventory_move,
        pick_sound = item_sounds.resource_inventory_pickup,
        drop_sound = item_sounds.sulfur_inventory_move,
        weight = 10*kg,
    },
    {
        type = "tool",
        name = "planetaris-compression-science-pack",
        icon = "__planetaris-arig__/graphics/icons/compression-science-pack.png",
        localised_description = {"item-description.science-pack"},
        subgroup = "science-pack",
        order = "h-b",
        stack_size = 200,
        default_import_location = "arig",

        inventory_move_sound = item_sounds.science_inventory_move,
        pick_sound = item_sounds.science_inventory_pickup,
        drop_sound = item_sounds.science_inventory_move,
        weight = 1*kg,
        durability = 1,
        durability_description_key = "description.science-pack-remaining-amount-key",
        factoriopedia_durability_description_key = "description.factoriopedia-science-pack-remaining-amount-key",
        durability_description_value = "description.science-pack-remaining-amount-value",
    },
    {
        type = "item",
        name = "planetaris-hyper-transport-belt",
        icon = "__planetaris-arig__/graphics/icons/hyper-transport-belt.png",
        subgroup = "belt",
        color_hint = { text = "5" },
        order = "a[transport-belt]-f[hyper-transport-belt]",
        inventory_move_sound = item_sounds.transport_belt_inventory_move,
        pick_sound = item_sounds.transport_belt_inventory_pickup,
        drop_sound = item_sounds.transport_belt_inventory_move,
        place_result = "planetaris-hyper-transport-belt",
        default_import_location = "arig",
        stack_size = 100,
        weight = 20*kg,
      },
      {
        type = "item",
        name = "planetaris-hyper-splitter",
        icon = "__planetaris-arig__/graphics/icons/hyper-splitter.png",
        subgroup = "belt",
        color_hint = { text = "5" },
        order = "c[splitter]-f[hyper-splitter]",
        inventory_move_sound = item_sounds.mechanical_inventory_move,
        pick_sound = item_sounds.mechanical_inventory_pickup,
        drop_sound = item_sounds.mechanical_inventory_move,
        place_result = "planetaris-hyper-splitter",
        default_import_location = "arig",
        stack_size = 50,
        weight = 40*kg,
      },
      {
        type = "item",
        name = "planetaris-hyper-underground-belt",
        icon = "__planetaris-arig__/graphics/icons/hyper-underground-belt.png",
        subgroup = "belt",
        color_hint = { text = "5" },
        order = "b[underground-belt]-f[hyper-underground-belt]",
        inventory_move_sound = item_sounds.mechanical_inventory_move,
        pick_sound = item_sounds.mechanical_inventory_pickup,
        drop_sound = item_sounds.mechanical_inventory_move,
        place_result = "planetaris-hyper-underground-belt",
        stack_size = 50,
        default_import_location = "arig",
        weight = 40*kg,
      },
      {
        type = "item",
        name = "planetaris-big-chest",
        icon = "__planetaris-arig__/graphics/icons/container.png",
        subgroup = "storage",
        order = "a[items]-d[big-chest]",
        inventory_move_sound = item_sounds.metal_chest_inventory_move,
        pick_sound = item_sounds.metal_chest_inventory_pickup,
        drop_sound = item_sounds.metal_chest_inventory_move,
        place_result = "planetaris-big-chest",
        stack_size = 50,
      },
      {
        type = "item",
        name = "planetaris-active-provider-big-chest",
        localised_name = {"entity-name.planetaris-active-provider-big-chest"},
        icon = "__planetaris-arig__/graphics/icons/active-provider-container.png",
        subgroup = "logistic-network",
        order = "b[storage]-f-a",
        inventory_move_sound = item_sounds.metal_chest_inventory_move,
        pick_sound = item_sounds.metal_chest_inventory_pickup,
        drop_sound = item_sounds.metal_chest_inventory_move,
        place_result = "planetaris-active-provider-big-chest",
        stack_size = 50,
      },
      {
        type = "item",
        name = "planetaris-passive-provider-big-chest",
        localised_name = {"entity-name.planetaris-passive-provider-big-chest"},
        icon = "__planetaris-arig__/graphics/icons/passive-provider-container.png",
        subgroup = "logistic-network",
        order = "b[storage]-f-b",
        inventory_move_sound = item_sounds.metal_chest_inventory_move,
        pick_sound = item_sounds.metal_chest_inventory_pickup,
        drop_sound = item_sounds.metal_chest_inventory_move,
        place_result = "planetaris-passive-provider-big-chest",
        stack_size = 50,
      },
      {
        type = "item",
        name = "planetaris-storage-big-chest",
        localised_name = {"entity-name.planetaris-storage-big-chest"},
        icon = "__planetaris-arig__/graphics/icons/storage-container.png",
        subgroup = "logistic-network",
        order = "b[storage]-f-c",
        inventory_move_sound = item_sounds.metal_chest_inventory_move,
        pick_sound = item_sounds.metal_chest_inventory_pickup,
        drop_sound = item_sounds.metal_chest_inventory_move,
        place_result = "planetaris-storage-big-chest",
        stack_size = 50,
      },
      {
        type = "item",
        name = "planetaris-buffer-big-chest",
        localised_name = {"entity-name.planetaris-buffer-big-chest"},
        icon = "__planetaris-arig__/graphics/icons/buffer-container.png",
        subgroup = "logistic-network",
        order = "b[storage]-f-d",
        inventory_move_sound = item_sounds.metal_chest_inventory_move,
        pick_sound = item_sounds.metal_chest_inventory_pickup,
        drop_sound = item_sounds.metal_chest_inventory_move,
        place_result = "planetaris-buffer-big-chest",
        stack_size = 50,
      },
      {
        type = "item",
        name = "planetaris-requester-big-chest",
        localised_name = {"entity-name.planetaris-requester-big-chest"},
        icon = "__planetaris-arig__/graphics/icons/requester-container.png",
        subgroup = "logistic-network",
        order = "b[storage]-f-e",
        inventory_move_sound = item_sounds.metal_chest_inventory_move,
        pick_sound = item_sounds.metal_chest_inventory_pickup,
        drop_sound = item_sounds.metal_chest_inventory_move,
        place_result = "planetaris-requester-big-chest",
        stack_size = 50,
      },
        {
        type = "item",
        name = "planetaris-arig-roboport",
        icon = "__planetaris-arig__/graphics/icons/arig-roboport.png",
        subgroup = "logistic-network",
        order = "c[signal]-a[roboport]-b",
        localised_description = {"item-description.roboport"},
        inventory_move_sound = item_sounds.roboport_inventory_move,
        pick_sound = item_sounds.roboport_inventory_pickup,
        drop_sound = item_sounds.roboport_inventory_move,
        place_result = "planetaris-arig-roboport",
        stack_size = 10,
        weight = 100*kg,
        default_import_location = "arig",
     },
        {
        type = "item",
        name = "planetaris-advanced-solar-panel",
        icon = "__planetaris-arig__/graphics/icons/advanced-solar-panel.png",
        subgroup = "energy",
        order = "d[solar-panel]-b[advanced-solar-panel]",
        inventory_move_sound = item_sounds.electric_large_inventory_move,
        pick_sound = item_sounds.electric_large_inventory_pickup,
        drop_sound = item_sounds.electric_large_inventory_move,
        place_result = "planetaris-advanced-solar-panel",
        stack_size = 20,
        weight = 20*kg,
        default_import_location = "arig",

     },
     {
        type = "item",
        name = "planetaris-supported-solar-panel",
        icon = "__planetaris-arig__/graphics/icons/supported-solar-panel.png",
        subgroup = "energy",
        order = "d[solar-panel]-c[supported-solar-panel]",
        inventory_move_sound = item_sounds.electric_large_inventory_move,
        pick_sound = item_sounds.electric_large_inventory_pickup,
        drop_sound = item_sounds.electric_large_inventory_move,
        place_result = "planetaris-supported-solar-panel",
        stack_size = 20,
        weight = 20*kg,
        default_import_location = "arig",
     },
     {
        type = "item",
        name = "planetaris-high-support-electric-pole",
        icon = "__planetaris-arig__/graphics/icons/high-support-electric-pole.png",
        subgroup = "energy-pipe-distribution",
        order = "a[energy]-e[planetaris-high-support-electric-pole]",
        inventory_move_sound = item_sounds.electric_large_inventory_move,
        pick_sound = item_sounds.electric_large_inventory_pickup,
        drop_sound = item_sounds.electric_large_inventory_move,
        place_result = "planetaris-high-support-electric-pole",
        stack_size = 50,
        weight = 10*kg,
        default_import_location = "arig",
     },
     {
        type = "item",
        name = "planetaris-water-harvester",
        icon = "__planetaris-arig__/graphics/icons/water-harvester.png",
        subgroup = "arig-production",
        order = "a-b",
        inventory_move_sound = item_sounds.electric_large_inventory_move,
        pick_sound = item_sounds.electric_large_inventory_pickup,
        drop_sound = item_sounds.electric_large_inventory_move,
        place_result = "planetaris-water-harvester",
        stack_size = 50,
        weight = 20*kg,
        default_import_location = "arig",
     },
  {
    type = "item",
    name = "planetaris-raw-diamond",
    icon = "__planetaris-arig__/graphics/icons/raw-diamond-1.png",
    pictures =
    {
      { size = 64, filename = "__planetaris-arig__/graphics/icons/raw-diamond-1.png",   scale = 0.5, mipmap_count = 4 },
      { size = 64, filename = "__planetaris-arig__/graphics/icons/raw-diamond-2.png", scale = 0.5, mipmap_count = 4 },
      { size = 64, filename = "__planetaris-arig__/graphics/icons/raw-diamond-3.png", scale = 0.5, mipmap_count = 4 },
      { size = 64, filename = "__planetaris-arig__/graphics/icons/raw-diamond-4.png", scale = 0.5, mipmap_count = 4 },
    },
    subgroup = "arig-processes",
    order = "b-a[raw]",
    stack_size = 100,
    weight = 2*kg,
    default_import_location = "arig",

    inventory_move_sound = item_sounds.sulfur_inventory_move,
    pick_sound = item_sounds.resource_inventory_pickup,
    drop_sound = item_sounds.sulfur_inventory_move,
  }
})